export const ROOT = '/';
export const HOME = '/home';
export const LOGIN = '/login';
export const LOGOUT = '/logout';
export const REGISTER = '/register';
export const PROFILE = '/profile';
export const MY_OFFERS = '/myoffers';
export const OFFERS = '/offers';
export const CREATE_OFFER = OFFERS + '/create';
